### ISSUE TITLE
New kernel-5.10_vmwgfx branch can't merge newer version

### ISSUE THREAD

**Issue by hmtheboy154** [maurossi/linux#19]
I'm trying to merge 5.10.1 but it got a lot of conflict and hard to fix them all. I tried both [kernel.org](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/?h=v5.10.1) and [android12-5.10](https://android.googlesource.com/kernel/common/+/refs/heads/android12-5.10) branch on Google's kernel/common and there are too many to handle.

**Comment by maurossi** [comment]
Are you really really sure that you are unable to perform the 2 reverts that are in 5.10.1 compared to 5.10?
I am going to just do that in my kernel-5.10_vmwgfx experimental branch.

Also I do not understand how two raid related commits could affect your Android builds.

Moreover what you say it's hard to fix, it really is, because android branches have commit spread and not sequential,
so it requires identifying them, list the essential ones and cherry-pick/apply one-by-one.

That is not planned in my branches, but feel free to use the sequence in my branch if you need it.
Closing as this issue is inappropriate, as I never said my starting point is AOSP kernels or merge would be clean (nobody can guarantee that anyway)

**Comment by hmtheboy154** [comment]
> Are you really really sure that you are unable to perform the 2 reverts that are in 5.10.1 compared to 5.10?
> I am going to just do that in my kernel-5.10_vmwgfx experimental branch.
> 
> Also I do not understand how two raid related commits could affect your Android builds.
> 
> Moreover what you say it's hard to fix, it really is, because android branches have commit spread and not sequential,
> so it requires identifying them, list the essential ones and cherry-pick/apply one-by-one.
> 
> That is not planned in my branches, but feel free to use the sequence in my branch if you need it.
> Closing as this issue is inappropriate, as I never said my starting point is AOSP kernels or merge would be clean (nobody can guarantee that anyway)

Thanks for the info .I actually switch to kernel-5.10rc7_vmwgfx instead and it merge fine now. Merging Google repo gave me less conflict that I can handle it.
