### ISSUE TITLE
Emergency Remount R/O

### ISSUE THREAD

**Issue by mrvayd** [maurossi/linux#20]
I am Installing android x86 7.1 rc1 on virtual box but it does not boot and shows the error Emergency Remount R/O

![image](https://user-images.githubusercontent.com/64084172/118385041-2116f880-b629-11eb-897f-b465df817ecd.png)

**Comment by maurossi** [comment]
Hi, this is not the place where issue like the one mentioned are processed, because it is my personal github space
and kernel branches here are by definition all experimental

However, in order to let you clarify which kernel version are you using?

if you see the problem is in android-x86 released version we may talk about the problem in the android-x86 forum
if the problem happens with the official android-x86 kernel versions

**Comment by mrvayd** [comment]
> Hi, this is not the place where issue like the one mentioned are processed, because it is my personal github space
> and kernel branches here are by definition all experimental
> 
> However, in order to let you clarify which kernel version are you using?
> 
> if you see the problem is in android-x86 released version we may talk about the problem in the android-x86 forum
> if the problem happens with the official android-x86 kernel versions

Oh Sorry Sir
