### ISSUE TITLE
A question about 4.4OPEMU branch

### ISSUE THREAD

**Issue by vohai2003** [maurossi/linux#21]
Hi,
There're some posts from sourceforge that leads me here, they said that the branch's buggy.
I want to know if I can replace the kernel of Android-x86 with this one without critical bugs.

**Comment by maurossi** [comment]
Hi, that branch is provided as it was, no guarantees, issue closed as this cannot be an issue, because it never worked in the first place. The fundamental problem to overcome is that opemu for 32bit targets was not avaible and in my undestanding it is still not available.
If you have problems you should contact the opemu mantainers, if you're still able to find them.
android-x86 SSSE3 minimum emulation required for x86 32bit builds is provided in the official kernel repo
